In [18]:
import pandas as pd 
import numpy as np

In [30]:
df = pd.read_csv('tips - tips.csv')

In [20]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [21]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [29]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [31]:
df['sex'] = df['sex'].map({'Female':0, 'Male':1})
df['smoker'] = df['smoker'].map({'No':0, 'Yes':1})
df['day'] = df['day'].map({'Sum':1, 'Mon':2, 'Tue':3, 'Wed':4, 'Thur':5, 'Fri':6, 'Sat':7})
df['time'] = df['time'].map({'Dinner':0, 'Lunch':1})

In [32]:
df.sample(5)

     total_bill   tip  sex  smoker  day  time  size
205       16.47  3.23    0       1  5.0     1     3
20        17.92  4.08    1       0  7.0     0     2
101       15.38  3.00    0       1  6.0     0     2
182       45.35  3.50    1       1  NaN     0     3
217       11.59  1.50    1       1  7.0     0     2

In [33]:
df.shape[0]

244

In [34]:
df.shape[1]

7

In [35]:
df.iloc[3:7, 1:4]

    tip  sex  smoker
3  3.31    1       0
4  3.61    0       0
5  4.71    1       0
6  2.00    1       0

In [40]:
df.sort_values(by='total_bill', ascending=False)

     total_bill    tip  sex  smoker  day  time  size
170       50.81  10.00    1       1  7.0     0     3
212       48.33   9.00    1       0  7.0     0     4
59        48.27   6.73    1       0  7.0     0     4
156       48.17   5.00    1       0  NaN     0     6
182       45.35   3.50    1       1  NaN     0     3
..          ...    ...  ...     ...  ...   ...   ...
149        7.51   2.00    1       0  5.0     1     2
111        7.25   1.00    0       0  7.0     0     1
172        7.25   5.15    1       1  NaN     0     2
92         5.75   1.00    0       1  6.0     0     2
67         3.07   1.00    0       1  7.0     0     1

[244 rows x 7 columns]