In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('/content/Churn_Modelling - Churn_Modelling.csv')

In [24]:
df.head(5)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
# 1. Find the total number of customers in each country.

In [6]:
df.groupby(['Geography']).size().reset_index(name='counts')

  Geography  counts
0    France    5014
1   Germany    2509
2     Spain    2477

In [8]:
# 2. Find the average credit score of customers based on gender.

In [64]:
df.groupby('Gender')['CreditScore'].mean().reset_index()

   Gender  CreditScore
0  Female   650.831389
1    Male   650.276892

In [20]:
# 3. Find the total number of customers who exited and customers who stayed.

In [26]:
df.groupby('Exited').size().reset_index(name='count')

   Exited  count
0       0   7963
1       1   2037

In [27]:
# 4. Find the average account balance in each country.

In [30]:
df.groupby('Geography')['Balance'].mean().reset_index(name='Avg_Balance')

  Geography    Avg_Balance
0    France   62092.636516
1   Germany  119730.116134
2     Spain   61818.147763

In [31]:
# 5. Find which age has the highest number of customers who exited the bank.

In [52]:
df[df['Exited']==1].groupby('Age').size().reset_index(name='counts').sort_values(by='counts', ascending=False).iloc[:1, :]

    Age  counts
28   46      91

In [53]:
# 6. Find the average estimated salary of active and inactive members.

In [66]:
df.groupby('IsActiveMember')['EstimatedSalary'].mean().reset_index(name='Avg_EstimatedSalary')

   IsActiveMember  Avg_EstimatedSalary
0               0        100767.203854
1               1         99452.965894

In [56]:
# 7. Find the churn count based on the number of products customers are using.

In [59]:
df[df['Exited']==1].groupby('NumOfProducts').size()

NumOfProducts
1    1409
2     348
3     220
4      60
dtype: int64

In [ ]:
# 8. Create a separate DataFrame containing country and region information, merge it with the
# main dataset using pd.merge(), and then find the average balance and average estimated
# salary by region.

In [75]:
region_df = pd.DataFrame({
    'Geography': ['France', 'Germany', 'Spain'],
    'Region': ['Western Europe', 'Central Europe', 'Southern Europe']
})
region_df

  Geography           Region
0    France   Western Europe
1   Germany   Central Europe
2     Spain  Southern Europe

In [76]:
df_merge = pd.merge(region_df, df, on='Geography')

In [77]:
df_merge.groupby('Region')['Balance'].mean('Balance').reset_index(name='Avg_balance')

            Region    Avg_balance
0   Central Europe  119730.116134
1  Southern Europe   61818.147763
2   Western Europe   62092.636516

In [80]:
df_merge.groupby('Region')['EstimatedSalary'].mean('EstimatedSalary').reset_index(name='Avg_EstimatedSalary')

            Region  Avg_EstimatedSalary
0   Central Europe        101113.435102
1  Southern Europe         99440.572281
2   Western Europe         99899.180814