In [2]:
# Pandas => 
    # -> Pandas is an open source library which is used for handle data manipulation.

In [1]:
import pandas as pd

In [5]:
# Data Structure of Pandas ::: 
    # 1. Series --> It stores only values not column name and it is one-dimensional 
    # 2. DataFrame --> It store values with column name, and it is multi-dimensional

In [7]:
a = pd.Series([1,2,3,4,5,6])
a

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [8]:
type(a)

pandas.core.series.Series

In [9]:
# DataFrame

In [12]:
a = {
    'Emp_id' : [1,2,3,4,5],
    'Name' : ['Abhi', 'Akanksha', 'Vikash', 'Divyansh', 'Rishi'],
    'Department' : ['IT', 'Sales', 'It', 'Sales', 'IT'],  
    'Salary' : [20000, 25000, 40000, 30000, 35000]
}

In [13]:
type(a)

dict

In [15]:
df = pd.DataFrame(a)
df

   Emp_id      Name Department  Salary
0       1      Abhi         IT   20000
1       2  Akanksha      Sales   25000
2       3    Vikash         It   40000
3       4  Divyansh      Sales   30000
4       5     Rishi         IT   35000

In [16]:
# Export this data into csv

In [17]:
df.to_csv('Emp_data.csv')

In [18]:
# Export this data into Excel

In [19]:
df.to_excel('New_Emp_data.xlsx')

In [20]:
# import the data

In [21]:
a = pd.read_csv('Emp_data.csv')
a

   Unnamed: 0  Emp_id      Name Department  Salary
0           0       1      Abhi         IT   20000
1           1       2  Akanksha      Sales   25000
2           2       3    Vikash         It   40000
3           3       4  Divyansh      Sales   30000
4           4       5     Rishi         IT   35000

In [2]:
### phone data

In [4]:
a = pd.read_csv('flipkart.csv')
a

,Model_Name,Rating,Rating_numbers,Reviews,Storage,Display,Camera,Battery,Processor,Price,Offers
0,"Samsung Galaxy F06 5G (Lit Violet, 64 GB)",4.2,"42,609 Ratings","2,577 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 1500 GB,17.02 cm (6.7 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,5000 mAh Battery,Dimensity 6300 Processor,"₹9,499",Bank Offer
1,"Samsung Galaxy F06 5G (Bahama Blue, 64 GB)",4.2,"42,609 Ratings","2,577 Reviews",4 GB RAM | 64 GB ROM | Expandable Upto 1500 GB,17.02 cm (6.7 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,5000 mAh Battery,Dimensity 6300 Processor,"₹9,499",Bank Offer
2,OPPO K13 5G with 7000mAh and 80W SUPERVOOC Cha...,4.5,"83,766 Ratings","4,878 Reviews",8 GB RAM | 256 GB ROM,16.94 cm (6.67 inch) Display,50MP + 2MP | 16MP Front Camera,7000 mAh Battery,Snapdragon 6 Gen 4 Processor,"₹20,999",Off on Exchange
3,OPPO K13 5G with 7000mAh and 80W SUPERVOOC Cha...,4.5,"83,766 Ratings","4,878 Reviews",8 GB RAM | 128 GB ROM,16.94 cm (6.67 inch) Display,50MP + 2MP | 16MP Front Camera,7000 mAh Battery,Snapdragon 6 Gen 4 Processor,"₹18,999",Off on Exchange
4,"vivo T4x 5G (Pronto Purple, 256 GB)",4.4,"1,63,990 Ratings","7,595 Reviews",8 GB RAM | 256 GB ROM,17.07 cm (6.72 inch) Display,50MP + 2MP | 8MP Front Camera,6500 mAh Battery,Dimensity 7300 5G Processor,"₹20,999",Bank Offer
5,"Samsung Galaxy F06 5G (Bahama Blue, 128 GB)",4.2,"22,443 Ratings","1,462 Reviews",6 GB RAM | 128 GB ROM | Expandable Upto 1500 GB,17.02 cm (6.7 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,5000 mAh Battery,Dimensity 6300 Processor,"₹11,999",Bank Offer
6,"vivo T4x 5G (Pronto Purple, 128 GB)",4.4,"1,63,990 Ratings","7,595 Reviews",8 GB RAM | 128 GB ROM,17.07 cm (6.72 inch) Display,50MP + 2MP | 8MP Front Camera,6500 mAh Battery,Dimensity 7300 5G Processor,"₹18,999",Bank Offer
7,"Samsung Galaxy F06 5G (Lit Violet, 128 GB)",4.2,"22,443 Ratings","1,462 Reviews",6 GB RAM | 128 GB ROM | Expandable Upto 1500 GB,17.02 cm (6.7 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,5000 mAh Battery,Dimensity 6300 Processor,"₹11,999",Bank Offer
8,"CMF by Nothing Phone 2 Pro (White, 128 GB)",4.4,"78,213 Ratings","5,366 Reviews",8 GB RAM | 128 GB ROM | Expandable Upto 2 TB,17.2 cm (6.77 inch) Display,50MP + 50MP + 8MP | 16MP Front Camera,5000 mAh Battery,Dimensity 7300 Pro 5G Processor,"₹18,999",Bank Offer
9,"Google Pixel 9A (Obsidian, 256 GB)",4.5,"8,289 Ratings",548 Reviews,8 GB RAM | 256 GB ROM,15.96 cm (6.285 inch) Full HD+ Display,48MP + 12MP | 12MP Front Camera,5100 mAh Battery,Tensor G4 Processor,"₹39,999",Bank Offer
10,"Samsung Galaxy S24 5G Snapdragon (Onyx Black, ...",4.6,"57,857 Ratings","3,470 Reviews",8 GB RAM | 128 GB ROM,15.75 cm (6.2 inch) Full HD+ Display,50MP + 12MP | 12MP Front Camera,4000 mAh Battery,8 Gen 3 Processor,"₹42,999",Bank Offer
11,"Samsung Galaxy F06 5G (Lit Violet, 128 GB)",4.2,"42,609 Ratings","2,577 Reviews",4 GB RAM | 128 GB ROM | Expandable Upto 1500 GB,17.02 cm (6.7 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,5000 mAh Battery,Dimensity 6300 Processor,"₹10,499",Bank Offer
12,"Apple iPhone 17 (Black, 256 GB)",4.6,"6,431 Ratings",331 Reviews,256 GB ROM,16.0 cm (6.3 inch) Super Retina XDR Display,48MP + 48MP | 18MP Front Camera,"A19 Chip, 6 Core Processor Processor",Apple One (1) Year Limited Warranty,"₹82,900",Bank Offer
13,"Apple iPhone 17 (Lavender, 256 GB)",4.6,"6,431 Ratings",331 Reviews,256 GB ROM,16.0 cm (6.3 inch) Super Retina XDR Display,48MP + 48MP | 18MP Front Camera,"A19 Chip, 6 Core Processor Processor",Apple One (1) Year Limited Warranty,"₹82,900",Bank Offer
14,"MOTOROLA Edge 60 Pro (Pantone Shadow, 512 GB)",4.4,"2,831 Ratings",207 Reviews,16 GB RAM | 512 GB ROM,17.02 cm (6.7 inch) Display,50MP + 50MP + 10MP | 50MP Front Camera,6000 mAh Battery,Dimensity 8350 Processor,"₹37,999",Bank Offer
15,"CMF by Nothing Phone 2 Pro (Light Green, 128 GB)",4.4,"78,213 Ratings","5,366 Reviews",8 GB RAM | 128 GB ROM | Expandable Upto 2 TB,17.2 cm (6.77 inch) Display,50MP + 50MP + 8MP | 16MP Front Camera,5000 mAh Battery,Dimensity 7300 Pro 5G Processor,"₹18,999",Off on Exchange
16,"Apple iPhone 17 (Mist Blue, 256 GB)",4.6,"6,431 Ratings",331 Reviews,256 GB ROM,16.0 cm (6.3 inch) Super Retina XDR Display,48MP + 48MP | 18MP Front Camera,"A19 Chip, 6 Core Processor Processor",Apple One (1) Year Limited Warranty,"₹82,900",Bank Offer
17,"CMF by Nothing Phone 2 Pro (Black, 256 GB)",4.4,"78,213 Ratings","5,366 Reviews",8 GB RAM | 256 GB ROM | Expandable Upto 2 TB,17.2 cm (6.77 inch) Display,50MP + 50MP + 8MP | 16MP Front Camera,5000 mAh Battery,Dimensity 7300 Pro 5G Processor,"₹20,999",Bank Offer
18,"Apple iPhone 16 (Teal, 128 GB)",4.6,"2,13,744 Ratings","6,869 Reviews",128 GB ROM,15.49 cm (6.1 inch) Super Retina XDR Display,48MP + 12MP | 12MP Front Camera,"A18 Chip, 6 Core Processor Processor",1 year warranty for phone and 1 year warranty ...,"₹64,900",Bank Offer
19,"Apple iPhone 16 (Black, 128 GB)",4.6,"2,13,744 Ratings","6,869 Reviews",128 GB ROM,15.49 cm (6.1 inch) Super Retina XDR Display,48MP + 12MP | 12MP Front Camera,"A18 Chip, 6 Core Processor Processor",1 year warranty for phone and 1 year warranty ...,"₹64,900",Bank Offer
20,"Samsung Galaxy F06 5G (Bahama Blue, 128 GB)",4.2,"42,609 Ratings","2,577 Reviews",4 GB RAM | 128 GB ROM | Expandable Upto 1500 GB,17.02 cm (6.7 inch) HD+ Display,50MP + 2MP | 8MP Front Camera,5000 mAh Battery,Dimensity 6300 Processor,"₹10,499",Bank Offer
21,"CMF by Nothing Phone 2 Pro (Orange, 128 GB)",4.4,"78,213 Ratings","5,366 Reviews",8 GB RAM | 128 GB ROM | Expandable Upto 2 TB,17.2 cm (6.77 inch) Display,50MP + 50MP + 8MP | 16MP Front Camera,5000 mAh Battery,Dimensity 7300 Pro 5G Processor,"₹18,999",Off on Exchange
22,"vivo X200T (Stellar Black, 256 GB)",4.7,776 Ratings,133 Reviews,12 GB RAM | 256 GB ROM,16.94 cm (6.67 inch) Full HD+ AMOLED Display,50MP + 50MP + 50MP | 32MP Front Camera,6200 mAh Battery,Dimensity 9400+ Processor,"₹59,999",Bank Offer
23,Samsung Galaxy S24 5G Snapdragon (Cobalt Viole...,4.6,"57,857 Ratings","3,470 Reviews",8 GB RAM | 256 GB ROM,15.75 cm (6.2 inch) Full HD+ Display,50MP + 12MP | 12MP Front Camera,4000 mAh Battery,8 Gen 3 Processor,"₹47,999",Off on Exchange